implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
tck/src/test/java/TestTokenClaimTypes.java
tck/src/test/java/TestTokenWithoutGroupsClaim.java
tck/src/test/resources/TokenNoGroups.json

Plus some minor refactoring of the provider to minimize the duplication in the Thorntail provider

[DO NOT MERGE] Configuring default groups claim and custom token headers

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
implementation/src/test/java/io/smallrye/jwt/auth/jaxrs/KeyLocationResolverTest.java
tck/src/test/java/io/smallrye/jwt/KeyLocationResolverTest.java

Fixes #83, #82, #81
All the key types are dealt with in `KeyLocationResolver` now so it will be easier to control it further, best attempt at resolving and calculating the public key only once.

Key resolution optimizations and other minor updates

---

implementation/pom.xml
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipal.java
implementation/src/test/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipalTestCase.java

* added a test dependency on the Json implementation
* added a unit test to make sure the changes didn't break existing functionality, also adding test cases for null values
* changed the default returned value to a JsonValue of null, instead of a raw null

Fix for #102

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath.java
testsuite/basic/src/test/resources/TokenGroupsPath.json

Correct processing of the standard scope claim

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
testsuite/basic/src/test/java/io/smallrye/jwt/KeyLocationResolverTest.java

Support for the keys on the file system

---

implementation/pom.xml
implementation/src/main/java/io/smallrye/jwt/JsonUtils.java
implementation/src/main/java/io/smallrye/jwt/KeyUtils.java
implementation/src/main/java/io/smallrye/jwt/SmallryeJwtUtils.java
implementation/src/main/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractor.java
implementation/src/main/java/io/smallrye/jwt/auth/cdi/CommonJwtProducer.java
implementation/src/main/java/io/smallrye/jwt/auth/cdi/JsonValueProducer.java
implementation/src/main/java/io/smallrye/jwt/auth/cdi/PrincipalProducer.java
implementation/src/main/java/io/smallrye/jwt/auth/cdi/RawClaimTypeProducer.java
implementation/src/main/java/io/smallrye/jwt/auth/cdi/SmallRyeJWTAuthCDIExtension.java
implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthorizationFilterRegistrar.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipalFactory.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipal.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipalFactory.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
implementation/src/test/java/io/smallrye/jwt/JsonUtilsTests.java
pom.xml
testsuite/basic/pom.xml

Fixes #101 
Aggregate code coverage results from implementation + TCK tests for Sonar reporting.

Resolve several issues reported by Sonar

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath.java
testsuite/basic/src/test/resources/TokenGroupsPath.json

Support for custom group claims with the comma-separated values

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParserTest.java
testsuite/basic/src/test/java/io/smallrye/jwt/config/JWTAuthContextInfoProviderTest.java

Fixes #146 
Also includes migration to Jakarta EE dependencies, supersedes #151 
@sberyozkin - let me know if this aligns with the intent.

Add time-to-live config option

---

implementation/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java
implementation/src/main/java/io/smallrye/jwt/build/JwtSignature.java
implementation/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java
implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java

Add JwtClaimsBuilder.json() method

---

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath.java
testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithSubPath.java
testsuite/basic/src/test/resources/TokenGroupsPath.json
testsuite/basic/src/test/resources/TokenSubPath.json

Support the claim paths with the namespaces

---

README.adoc

Add the configuration section to README

---

implementation/src/main/java/io/smallrye/jwt/KeyUtils.java
implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSigningUtils.java

A simple update to check the context loader too as some resource loading methods do not work correctly in the Quarkus dev mode

Update some resource loading methods to check the context class loader

---

implementation/src/main/java/io/smallrye/jwt/build/JwtSignature.java
implementation/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java

Allow for setting JWE headers after innerSign

---

.github/project.yml

Reverts smallrye/smallrye-jwt#271

Revert "Release Smallrye JWT 2.2.0"

---

implementation/src/main/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractor.java
implementation/src/test/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractorTest.java

Support custom schemes for the custom headers

---

doc/modules/ROOT/pages/configuration.adoc
doc/modules/ROOT/pages/generate-jwt.adoc

This PR mainly syncs the JWT generation docs with those in Quarkus and fixes a small typo

Update the documentation

---

implementation/jwt-build/pom.xml
implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignPS256Test.java
implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
pom.xml

Better support for the PS256 test

---

.github/project.yml

Reverts smallrye/smallrye-jwt#352

Revert "Release Smallrye JWT 2.4.1"

---

pom.xml

Reverts smallrye/smallrye-jwt#346

Revert "Bump smallrye-parent from 23 to 25"

---

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipal.java

Corrected toString implementation when the groups are empty

Corrected toString implementation

---

implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java
pom.xml
testsuite/tck/pom.xml
testsuite/tck/src/test/java/io/smallrye/jwt/tck/SmallRyeJWTArchiveProcessor.java

Fixes #337
@radcortez I'm seeing some strange TCK dep issue with 4.6.0.Final - hoping it is a problem with the cached staged repo

Update MP Config version to 2.0

---

implementation/common/pom.xml
implementation/common/src/main/java/io/smallrye/jwt/algorithm/KeyEncryptionAlgorithm.java
implementation/common/src/main/java/io/smallrye/jwt/util/JWTUtilMessages.java
implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java
implementation/common/src/test/java/io/smallrye/jwt/util/GenerateSecretFromKeyEncryptionAlgoTest.java
implementation/common/src/test/java/io/smallrye/jwt/util/GenerateSecretFromSignatureAlgoTest.java
implementation/common/src/test/java/io/smallrye/jwt/util/KeyUtilsTest.java

Add methods for secret key generation (#342)

---

.github/project.yml

Please see the [commits](https://github.com/smallrye/smallrye-jwt/compare/fe8e21b...ad308fb) and the [affected source](https://github.com/smallrye/smallrye-jwt/compare/fe8e21b..ad308fb).

Release SmallRye JWT 2.4.4

---

.github/project.yml

Commits (https://github.com/smallrye/smallrye-jwt/commits/main):
https://github.com/smallrye/smallrye-jwt/commit/2cd75acf1e29aa153d242578b0dbad6a38ff0d08
https://github.com/smallrye/smallrye-jwt/compare/979fe1a...e1d4bc9
https://github.com/smallrye/smallrye-jwt/compare/979fe1a..e1d4bc9

Release SmallRye JWT 3.1.0

---

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplLogging.java
implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java

Fixes #448
Just a minor cleanup

Fix the error messages referring to 'key-location' and remove the unused log message

---

testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverKeyContentTest.java

It is already TCK tested - just adding one extra local test to verify it

Verify fully formatted PEM key can be accepted and invalid key causes UnresolvedKeyException

---

.github/project.yml

Commits:
https://github.com/smallrye/smallrye-jwt/compare/c0e95b2...a11f218
https://github.com/smallrye/smallrye-jwt/compare/c0e95b2..a11f218

Release SmallRye JWT 3.1.1

---

.github/project.yml

All Commits:
https://github.com/smallrye/smallrye-jwt/compare/03558f7...76ae8df
https://github.com/smallrye/smallrye-jwt/compare/03558f7..76ae8df

Release SmallRye JWT 3.2.0

---

.github/project.yml

All Commits:
https://github.com/smallrye/smallrye-jwt/compare/495e2b8...77676d9
https://github.com/smallrye/smallrye-jwt/compare/495e2b8...77676d9

Release SmallRye JWT 3.2.1

---

pom.xml

It brings jose4j 0.7.9 as a TCK dep

Bump MP JWT version to 1.2.2

---

.github/project.yml

All Commits:
https://github.com/smallrye/smallrye-jwt/compare/495e2b8...50e3dc5
https://github.com/smallrye/smallrye-jwt/compare/495e2b8...50e3dc5

Release SmallRye JWT 3.3.0

---

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java

Fix the problem with the zero expiry grace period

---

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java
implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java

Provide cause with signingKeyCanNotBeLoadedFromLocation

---

implementation/jwt-http-mechanism/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java

Fixes https://github.com/smallrye/smallrye-jwt/issues/656

identitystore integration

---

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalMessages.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/UnmatchedTokenKidException.java
implementation/jwt-http-mechanism/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java
implementation/jwt-http-mechanism/src/main/java/io/smallrye/jwt/auth/mechanism/MechanismLogging.java

Distinguish between unresolvable and invalid keys

---

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AwsAlbKeyConfigurationValidator.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AwsAlbKeyResolver.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AwsAlbKeyResolverLogging.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AwsAlbKeyResolverMessages.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalLogging.java
implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalMessages.java
implementation/jwt-auth/src/test/java/io/smallrye/jwt/auth/principal/AwsAlbKeyConfigurationValidatorTest.java
implementation/jwt-auth/src/test/java/io/smallrye/jwt/auth/principal/AwsAlbKeyResolverTest.java

Validates AWS-specific configuration and writes additional log statements

AWS Configuration Validation and Logging

---

implementation/common/src/main/java/io/smallrye/jwt/algorithm/KeyEncryptionAlgorithm.java
implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java
implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java
implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java

Fixes [734](https://github.com/smallrye/smallrye-jwt/issues/734)

Support "Direct encryption with shared symmetric key"

---

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/Jwt.java
implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java

Quick fix for the Javadocs issue

Fix the self-closing element JavaDocs issue

---

implementation/jwt-auth/src/main/java/io/smallrye/jwt/JsonUtils.java

See https://github.com/quarkusio/quarkus/issues/42748 for more details.

Avoid instantiating too many JsonProviders
