implementation/pom.xml, implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthFilter.java, implementation/src/test/java/io/smallrye/jwt/auth/jaxrs/JWTAuthFilterTest.java
This fixes a potential `NullPointerException` situation and adds support for cookie and custom HTTP header bearer tokens to `JWTAuthFilter`. There are several test cases added here along with two `test` scope Maven dependencies to support them.
* Replace System.err.printf statements with logging and avoid printing the token to the log.
* Add test cases for JWTAuthFilter#getBearerToken and add two test dependencies (Mockito and Jersey to support tests).
=> Prevent NPE in JWTAuthFilter and handle other token locations

implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/test/java/io/smallrye/jwt/auth/jaxrs/KeyLocationResolverTest.java
The imports order have changed because I'm using the default formatter of IntelliJ.
I can fix that if you want but I don't know the rules.
=> Add an error message when a public key is loaded as a resource using mp.jwt.verify.publickey.location

implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
The original function I added was a quick attempt to have it reused from Thorntail but the code for setting the cookies is not reusable. The error message in the non-optional producer method is more user friendly as well (per @starksm64 suggestion)
=> Removing the monolitic header/groups function and updating the error message

implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Also adding more getters to the provider in case Thorntail will want to use some of the new properties. Also avoiding caching the public key if it is a HTTPS URL based cache as it would defeat the purpose of the rotation.
=> Adding a jwks.refresh-interval property

implementation/pom.xml, implementation/src/main/java/io/smallrye/jwt/auth/cdi/ClaimValueProducer.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/ClaimValueWrapper.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/CommonJwtProducer.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/ClaimQualifier.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/ClaimValueProducerIT.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/JsonValueProducerTest.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/PrincipalProducerIT.java, implementation/src/test/resources/META-INF/beans.xml, pom.xml
This is where I am going with #113. I added some integration tests with Weld to make sure this actually works with a real CDI provider as well. The management/version for the failsafe plugin could probably be moved up into smallrye/parent sooner or later.
A few things to think about:
1. I think `CommonJwtProducer.wrapClaimValue` is no longer needed - not sure of downstream impact in Thorntail, etc. The updated code will get the claim value directly and only wrap in `Optional` if necessary versus defaulting to wrapping it and unwrapping if necessary.
2. I extended `ClaimValueWrapper`, but I believe the changes could be made directly therein if item 1 is true. I think the wrapper should _always_ delegate to the `JsonWebToken` for value lookup.
Thoughts?
=> Support ClaimValue dynamic calls to JWT claims, add integration tests

implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
The file resources are also checked first, while the URL check when neither file or classpath scheme is used is tried at the very end.
Fixes #108
=> Reverting to checking the scheme without URI conversion to avoid side-effects on Win

implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Verified against the latest Thorntail and Quarkus
=> Remove ApplicationScope from getOptionalJwtAuthContextInfo

implementation/src/main/java/io/smallrye/jwt/auth/cdi/NullJsonWebToken.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/PrincipalProducer.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/ProviderExtensionSupport.java
Making `NullJsonWebToken` independent will help clean up a bit some of Quarkus code, while `ProviderInjectionSupport` will help with Thorntail CDI clean up and WildFly might use it too.
Fixes #132.
=> Move NullJsonWebToken into an independent class and add ProviderInjectionSupport

implementation/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java
The HttpMessageContext.doNothing() method results in AuthenticationStatus.NOT_DONE to be returned: -
https://javaee.github.io/javaee-spec/javadocs/javax/security/enterprise/authentication/mechanism/http/HttpMessageContext.html#doNothing--
https://javaee.github.io/javaee-spec/javadocs/javax/security/enterprise/AuthenticationStatus.html#NOT_DONE
EE Security allows for mechanisms to be called pre-emptive i.e. they are given an opportunity to authenticate if they can even if the specific resource does not require it - NOT_DONE can be returned in those cases if authentication as not attempted AND it was not required.
If however authentication is required the mechanism should instead be returning AuthenticationStatus.SEND_FAILURE to trigger a 401 to the calling client. …
=> Check if the resource is protected to select the appropriate response.

implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthenticationFilter.java, implementation/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
This pull request is a proposal to reduce the verbosity of some of the logging within SmallRye JWT.
It is common within an application server environment that the logging would be configured to log messages at INFO or higher, however it is also general desirable to avoid logging that results in per-request logging for something that is "normal operation" for the server.
For many of the messages logged although they may represent an error for a specific request they are normal operation for the server, a production server should normally expect to receive both valid and invalid tokens so provided the invalid tokens are handled correctly (i.e. rejected) it is not beneficial to log each of them to any console or log file output.
Also by logging to debug it makes it easier to log the actual …
=> Reduce verbosity of logging.

implementation/src/main/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractor.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/SmallRyeJWTAuthCDIExtension.java, implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthenticationFilter.java, implementation/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipalFactory.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTParser.java, implementation/src/test/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractorTest.java
Integrating SmallRye components into the WildFly application server the integrated components are added to the server as a module, within WildFly each module is loaded within it's own ClassLoader which is subsequently shared across deployments.
SmallRye JWT has been making use of a static variable to cache the JWTCallerPrincipalFactory, this has a side effect of caching application specific configuration and CDI beans.  For single deployment processes or processes restarted for each redeployment the static emulates @ApplicationScoped but in WildFly it is a global scope.
This pull request is to propose moving the caching into an @ApplicationScoped bean so in all existing scenarios the behaviour should remain the same.
The existing behaviour of …
=> Cache JWTCallerPrincipalFactory within @ApplicationScoped bean.

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java
Multiple Object instances are created per-request which will need to be garbage collected when we have a way to avoid this.
=> Don't use a Stream for a simple check

implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java
Presently when using location based resolution there is no attempt to decode using Base64 URL encoding, this is required in section 9.2 of the MicroProfile JWT specification.
=> Attempt to decode using Base64URL for JWK and JWKS.

implementation/src/main/java/io/smallrye/jwt/SmallryeJwtUtils.java, implementation/src/main/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractor.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/src/test/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractorTest.java
Add a `smallrye.jwt.token.schemes` configuration value to support additional token schemes, such as DPoP.
=> Add support for custom token schemes

implementation/pom.xml, pom.xml, testsuite/basic/pom.xml
Fixes #168 
Note that the umbrella `javaee-api` dependency has been replaced with the specific APIs that are directly used. This should make it more transparent what is used. This also includes and supersedes #151 .
=> Migrate to Jakarta EE dependencies

implementation/src/main/java/io/smallrye/jwt/algorithm/ContentEncryptionAlgorithm.java, implementation/src/main/java/io/smallrye/jwt/algorithm/KeyEncryptionAlgorithm.java, implementation/src/main/java/io/smallrye/jwt/algorithm/SignatureAlgorithm.java, implementation/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/src/main/java/io/smallrye/jwt/build/JwtEncryptionBuilder.java, implementation/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/src/main/java/io/smallrye/jwt/build/JwtSignatureBuilder.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSigningUtils.java, implementation/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #174.
Fixes #173.
The main changes: 
- new `sign`, `innerSign` and `encrypt` methods which accept a key location. 
- enforcing RSA key size to 2048 bits
- better docs
- few more signature/enc algorithm enums
=> Add sign/innerSign/encrypt methods accepting a key location, checking  RSA key size, better docs

implementation/src/main/java/io/smallrye/jwt/KeyFormat.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
`KeyFormat` property is introduced in preparation for #85 and also for `KeyLocationResolver` to avoid trying all the supported formats (in the worst cases, if it is HTTPS based Base64URL-encoded JWK set, the key will be loaded on the 5th attempt).
I've been thinking if `KeyStoreType` would be better given that it will be `JKS` which will be added next. But then for example an individual PEM key is not exactly a key store though it can be seen as such. So I've added a note in the docs it can be either the format or store type
=> Add a key format property

docs/pom.xml, implementation/pom.xml, pom.xml, release/pom.xml, testsuite/basic/pom.xml, testsuite/pom.xml
We have been discussing this week the need to be able to tag maintenance releases that contain bug fixes only without new enhancements, our integration within WildFly is now in the closing stages before we tag we should move to the next minor in case micro bug fix releases are needed.
=> Move version to 2.1

implementation/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java
Currently the classes `JWTHttpAuthenticationMechanism.java` and `DefaultJWTParser.java` cannot be used in unit tests, since there is no way to inject their dependencies. This PR adds an additional constructor for manual dependency injection.
=> Add constructor to allow manual dependency injection in tests

README.adoc, implementation/src/main/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractor.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/src/test/java/io/smallrye/jwt/auth/AbstractBearerTokenExtractorTest.java
- add new property `smallrye.jwt.always-check-authorization` with default false
- evaluate `smallrye.jwt.always-check-authorization` in `AbstractBearerTokenExtractor` if set to true, fallback to `Authorization` header even if `tokenHeaderName` is set to `Cookie` but cookie is empty
- Add smallrye.jwt.always-check-authorization` in documentation with description
As discussed with @sberyozkin on zulipchat
=> Add configuration to always check `Authorization` header

implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java, testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsPath2.java, testsuite/basic/src/test/java/io/smallrye/jwt/TestTokenWithGroupsString.java, testsuite/basic/src/test/resources/TokenGroupsPath2.json, testsuite/basic/src/test/resources/TokenGroupsString.json
This PR adds a support for tokens where `groups` is a string (reported by a Quarkus Ping Identity user), I've also updated the code to support `groups` being a complex object
=> Support the cases when groups is a string or complex object

implementation/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java
Building locally the build time formatting is modifying the source, this PR just contains the modifications.
I am not sure how but could be nice if CI could fail builds that result in formatting changes as it is a sign formatting has not occurred before the commit was made.
=> Correction due to build time formatting.

pom.xml, testsuite/pom.xml, testsuite/tck/pom.xml, testsuite/tck/src/test/java/io/smallrye/jwt/tck/OptionalAwareSmallRyeJWTAuthCDIExtension.java, testsuite/tck/src/test/java/io/smallrye/jwt/tck/SmallRyeJWTArchiveProcessor.java, testsuite/tck/src/test/java/io/smallrye/jwt/tck/SmallRyeJWTAuthJaxRsFeature.java, testsuite/tck/src/test/java/io/smallrye/jwt/tck/SmallRyeJWTExtension.java, testsuite/tck/src/test/java/io/smallrye/jwt/tck/TestApplication.java, testsuite/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, testsuite/tck/src/test/resources/arquillian.xml, testsuite/tck/src/test/resources/jboss-web.xml, testsuite/tck/src/test/resources/microprofile-config-local.properties, testsuite/tck/src/test/resources/tck-base-suite.xml
Here is the initial work to run the TCK directly in the project.
Still some tests failures, probably related with missing setup that need to be debugged on a case by case basis.
This is using `io.smallrye.jwt.auth.jaxrs.JWTAuthenticationFilter` to apply the security context.
A few considerations:
- It seems the filters are not used either in Elytron (uses their internal HttpServerAuthenticationMechanism) or Quarkus (they implement their own with Vert.x).
- The filters were not being testes previously, so some of the failures related with the filters I'm not sure if they are cause by the setup or some bug in the filter.
- Do we want to keep the filters and change them is required? Is anyone else using them?
- The `SmallRyeJWTAuthCDIExtension` has Optional injection turned off by default, …
=> Add TCK tests to project.

implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
Recently I had to debug my usage of smallrye-jwt (using a local jwks.json). This PR tries to improve debugging in this area:
- First of all, log-debug AuthContextInfo in KeyLocationResolver
- 2nd, no more duplicate "Failed to load a key from [...]" log-debug message
=> KeyLocationResolver, give debug information about authContextInfo

implementation/src/main/java/io/smallrye/jwt/auth/cdi/RawClaimTypeProducer.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/ClaimInjectionTest.java, implementation/src/test/resources/token-claims.json
This is some work to support https://github.com/eclipse/microprofile-jwt-auth/issues/127.
An interesting this is that the spec includes support for `Boolean`, but there is not TCK test for it, so it was never implemented in SmallRye JWT.
While doing the work, I've also found another issue. Our `ClaimValue` support does not unwrap `JsonValue` to wrapper primitive types. So if you try to inject a custom `ClaimValue<Long>` you will get a `ClassCastException`, since for some reason we are wrapping the original claimSet in `DefaultJWTCallerPrincipal#fixJoseTypes`
This doesn't happen with `ClaimValue<Long>` of `aud` for instance, because we are not remapping that claim name so it works fine.
I think we need to change this and don't modify the original claims set. This will fix the injection for …
=> Support Boolean and boolean as a valid injection point.

README.adoc, doc/modules/ROOT/pages/generate-jwt.adoc
Added documentation for the encrypt and sign key locations.
https://github.com/smallrye/smallrye-jwt/issues/221
=> Add documentation for smallrye encrypt and sign properties

implementation/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtProviderImpl.java, implementation/src/main/java/io/smallrye/jwt/build/spi/JwtProvider.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
To support a Quarkus user who needs to enhance an injected or parsed token. This method is a thin wrapper around a method accepting a Map of claims
=> Add a method to init JwtClaimsBuilder from JsonWebToken

README.adoc
Testsuite and documentation link seem to be outdated and don't work any more. I updated them to the new locations and added a link for the testsuite/baisc.
=> Fix testsuite and doc links in readme

implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSigningUtils.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
This PR addresses this [StackOverflow question](https://stackoverflow.com/questions/61713369/unable-to-create-instance-of-jwtclaimsbuilder-in-quarkus-application)
I'd like to release smallrye-jwt-2.1.2 once this PR is resolved
=> Load the token resource from the file system

implementation/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtProviderImpl.java, implementation/src/main/java/io/smallrye/jwt/build/spi/JwtProvider.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
This PR supports a case where a JSON is already available, example, read from DB etc. It will make it even simpler to turn any custom JSON into custom JWT claims. 
Next I'll add more configuration properties so that 'technical'/standard claims like `issuer` and `exp` or headers like `kid` can be configured plus a set of shortcuts like `Jwt.sign(jsonObject)`
=> Support for creating tokens from JsonObject

implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/config/JWTAuthContextInfoProviderTest.java
We've had numerous Quarkus related feedback in that throwing the exception if no public key location is available at the CDI Producer method time affects the developer experience badly, the latest feedback is [here](https://github.com/quarkusio/quarkus/issues/5211#issuecomment-589952165).
This PR does not change anything fundamentally, right now `KeyLocationResolver` is a central place where the keys are resolved anyway, the process which fails if the location is invalid, so if location is not set or the key is not inlined, then the same `UnresolvableKeyException` is thrown.
Note I may need to revisit the whole idea of loading the key content in `KeyLocationResolver` and try to at least pre-load it for the local resources in the producer. Https resources are trickier to preload reliably …
=> Support Quarkus Dev mode with the context without the keys

implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JAXRSLogging.java, implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthenticationFilter.java, testsuite/tck/src/test/resources/tck-base-suite.xml
To fix TCK test EmptyTokenTest in MP 1.2.
=> Throw NotAuthorizedException if a JWT is sent to an unauthenticated endpoint and is not valid

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/src/main/java/io/smallrye/jwt/build/JwtEncryptionBuilder.java, implementation/src/main/java/io/smallrye/jwt/build/JwtSignatureBuilder.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSigningUtils.java, implementation/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
This PR:
* Deprecates a number of builder API methods and introduces more compact alternatives.
For example, when we do:
`Jwt.claims("somejson.json").jws().signatureKeyId("kid").sign()`, `signature` in `signatureKeyId` is duplicating what both `jws()` and `sign` imply. Similarly for all other deprecated methods. The IDE also helps with algorithm related methods, for ex, when we do `jws().algorithm(...)` we see a `SignatureAlgorithm` parameter type.
In fact, originally I did plan for `Jwt.claims("somejson.json").jws().keyId("kid").sign()` - the compactness of the API is a big priority, but then I somehow got offtrack when I was looking at the inner token case, where the token is signed and encrypted:
```
Jwt.claims().jws().keyId().innerSign().keyId().encrypt();
```
Here I thought well, 2 …
=> Minor JWT build improvements

implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/src/test/java/io/smallrye/jwt/config/JWTAuthContextInfoProviderTest.java, testsuite/tck/src/test/resources/tck-base-suite.xml
This requires https://github.com/eclipse/microprofile-jwt-auth/pull/190.
=> Support mp.jwt.verify.publickey.algorithm.

implementation/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java
A slight refactor of the JWTEncryptionImpl.
Merged some of the code paths
Corrected the Exception named in the ImplMessage to match that of the API
=> Refactor JWTEncryptionImpl to remove redundant code paths

implementation/src/main/java/io/smallrye/jwt/KeyUtils.java, implementation/src/main/java/io/smallrye/jwt/ResourceUtils.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSigningUtils.java, implementation/src/main/java/io/smallrye/jwt/config/ConfigMessages.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/config/JWTAuthContextInfoProviderTest.java
This PR does the following:
- Moves the resource loading code into `ResourceUtils` to make it consistent across all of smallrye-jwt, so that the keys (for signing, encrypting, verifying, decrypting), as well as the claim resources (builder API) can be loaded from everywhere.
- Started with enforcing early that `mp.jwt.publickey.location` points to the actual key(s), this in fact will be closer to the spec expectations. (I'm still keeping initializing `http(s)` locations in `KeyLocationResolver` as Keycloak/etc can be a few secs behind at the start up time, but I'll probably, in the next phase, will try to init them early as well, and if it fails - then let `KeyLocationResolver` handle it...). CC @FroMage, Stephane has asked for it after spending a few hours chasing the problem with an …
=> Improve the resource loading code

implementation/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/src/test/java/io/smallrye/jwt/build/JwtClaimShortcutsTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java, implementation/src/test/resources/customClaim.json
This PR continues with making the builder API as compact as possible, introduces the shortcuts to optimize some flows.
1. In the flow where the claims are built from the empty builder, `Jwt.claims()` transition is now optional, every time I see `Jwt.claims().claim("a", "b")` I think this is suboptimal. 
So, instead of `Jwt.claims().issuer("issuer").subject("sub").sign()` once can just do `Jwt.issuer("issuer").subject("sub").sign()`.
2. Creates `sign()`, `encrypt` and `innerSignAndEncrypt` shortcuts to optimize the flows where the keys are configured and where the default RSA algorithms are used:
- `Jwt.claims("/token.json").sign()` is equivalent to `Jwt.sign("/token.json")`
(same for the maps and jsonobject)
- `Jwt.claims("/token.json").jwe().encrypt()` is equivalent to …
=> JWT Builder shortcuts

doc/modules/ROOT/pages/configuration.adoc, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParserTest.java
Darran @darranl has identified the specification problem where RSA keys with the `1024` bit length are required to be supported but neither TCK enforces it nor smallrye-jwt itself supports such keys. It concerns the WildFly security team. 
Darran has proposed to drop `1024` key length completely in `MP JWT 1.2` (which is very sound since MP JWT builds on top of the Jose specs and the JWA spec in particular requiring a minimum `2048` RSA key length) but due to the pushback we will have it in MP JWT 1.2.
This PR makes sure it is supported OOB with an option for the users to block `1024` bit length keys
=> Support public RSA keys with 1024 bit length

implementation/pom.xml, pom.xml, release/pom.xml, testsuite/basic/pom.xml, testsuite/pom.xml, testsuite/tck/pom.xml
Hi All, I'd like to move the version to `2.2.0` and release since `JWTParser` has had a new methods added and the decryption code has also been backported from `mpjwt12`. I suspect the lifespan of `2.2.x` won't be long given that `MP JWT 1.2` is hopefully is getting close and `mpjwt12` will set the version to `3.0.0`, but I thought it would be better to increase a minor version now anyway as there could be another couple of `2.2.x` releases in between....
I don't really mind much to do the next release as `2.1.3` since no breaking changes have been introduced but again I'll feel better when showing the release log to the Quarkus QE team if it becomes `2.2.0` :-)
=> Update the version to 2.2.0.SNAPSHOT

implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParserTest.java, testsuite/tck/src/test/resources/tck-base-suite.xml
The verification key is now relaxed by default on the MP JWT 1.2 branch
=> Relax the key validation by default on MP JWT 1.2 branch

implementation/src/main/java/io/smallrye/jwt/auth/principal/PrincipalMessages.java, testsuite/basic/src/test/java/io/smallrye/jwt/config/JWTAuthContextInfoProviderTest.java
Hello,
fix for JWT TTL verification failed message. Fixes the following wrong kind of ParseException message:
~~~
io.smallrye.jwt.auth.principal.ParseException: The Expiration Time (exp=NumericDate{1594285731 -> Jul 9, 2020, 11:08:51 AM CEST}) claim value cannot be more than 60 minutes in the future relative to Issued At (iat=NumericDate{1594283931 -> Jul 9, 2020, 10:38:51 AM CEST})
~~~
The maxTimeToLiveSecs attribute is in seconds instead of minutes. The ParseException should mention seconds and not minutes.
Thanks.
Regards.
=> Fix JWT TTL time units message

doc/modules/ROOT/pages/configuration.adoc, implementation/src/main/java/io/smallrye/jwt/auth/cdi/JWTCallerPrincipalFactoryProducer.java, implementation/src/main/java/io/smallrye/jwt/auth/cdi/SmallRyeJWTAuthCDIExtension.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/CustomJWTCallerPrincipalFactoryTest.java, implementation/src/test/java/io/smallrye/jwt/auth/cdi/JWTCallerPrincipalFactoryProducerTest.java
Fixes #144 
Fixes #193 
This is PR has been created to complete Andreas's effort (see #194) with a few minor differences. Here is the summary:
- `JWTCallerPrincipalFactory` is now injected into `DefaultJWTParser`
- I've added a producer and moved the serviceloader related code there - it is important to retain this option to avoid breaking the existing expectations around loading the factories
- TCK tests are passing, added 2 simple unit tests, updated the docs
- Added a [test in Quarkus](https://github.com/quarkusio/quarkus/compare/master...sberyozkin:smallrye-jwt-2.2.1?expand=1) as well
CC @andreas-eberle
=> Inject JWTCallerPrincipalFactory

doc/modules/ROOT/pages/configuration.adoc, implementation/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DecryptionKeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/src/test/java/io/smallrye/jwt/auth/principal/DecryptionKeyLocationResolverTest.java, implementation/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java, testsuite/basic/src/test/resources/secretKey.jwk
Fixes #126 
This is the final PR before the planned 2.2.1 release and resolves a long pending issue to do with configuring the symmetric key locations, with some good user interest around it. Now we'll have a comprehensive support for securing and validating JWT tokens with all sort of keys which will work well in a variety of cases.
PR itself is basic, I had to add a new property to avoid overloading the existing `publickey.location` one.
=> Support for the configured secret key location

implementation/src/main/java/io/smallrye/jwt/KeyUtils.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java, implementation/src/main/java/io/smallrye/jwt/auth/principal/JWTParser.java, implementation/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/src/test/java/io/smallrye/jwt/build/JwtSignTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java
Fixes #290. 
Quarkus users have to manually create `SecretKey` when they want to sign the token with a password so this PR adds a few shortcuts making it very easy to do.
=> Simpler token symmetric signing and encryption support

doc/modules/ROOT/pages/configuration.adoc
As a follow-up to https://github.com/quarkusio/quarkus/issues/13091
this commit fixes the case of SmallRye in .
This is useful for Quarkus as it allows copy-and-pasting the relevant
section to the Quarkus JWT guide.
=> Correct letter case of SmallRye in documentation

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #327 
The NPE reported at the StackOverflow page is to do with the key being null, so this PR ensures it won't happen again and makes it consistent between the signature and encryption implementations.
Also the key format in that issue is PKCS12 which is not currently supported - perhaps we can do it in 3.0.0
I'd like to release 2.4.0 after this PR is reviewed/merged
=> Better handling of the wrong JWT build key locations

implementation/common/src/main/java/io/smallrye/jwt/util/ResourceUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java
Fixes #344 
Also, minor refactoring of ResourceUtils to be able to use the utility code which gets the stream only, without converting it to String, realized it can be handy while I was coding some KeyStore.load
=> Use UUID for the 'jti' claim, and update ResourceUtils to have a separate InputStream utility

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
This PR adds `expiresIn` helper to set the `exp` claim which should make it much easier to set the custom expiry claim as opposed to the users having to manually add the lifespan to the current issued time. Plus some minor cleanup
=> Support for expireIn build method and other minor cleanup

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/mechanism/MechanismLogging.java
Fixes #372 
Currently, exception handling in `JWTHTTPAuthenticationMechanism` issues status code 401 when the public key is corrupted or unavailable.
=> Issue#372 Status code should be 500 when public key cannot be resolved

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/jaxrs/JAXRSLogging.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/jaxrs/JWTAuthenticationFilter.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/mechanism/JWTHttpAuthenticationMechanism.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/mechanism/MechanismLogging.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalMessages.java
@MikeEdgar - have a look please - I've also updated the JAX-RS filter 
@SoniaZaldana FYI, I also had to update the `MechanismLogging.noUsableKey` log message a tiny bit, dropped `...public...` in the key description - it can also be a private decryption key (standard from MP JWT 1.2) or a symmetric key (supported at the smallrye-jwt level only). I think we can improve it further down the line with the key type specific exceptions as well...
You are also welcome to review (I'll be able to request a review when you become a committer )
By the way, for 3.0.0, I think moving the http mechanism into its own module would be the right idea :-) as the core module would better be transport agnostic; similarly to how the jaxrs code got moved into its own module
Thanks
=> Report UnresolvableKeyException in the inner-sign/decrypt case, update JAX-RS filter too

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #364
This PR adds a new `smallrye.jwt.new-token.audience` property - for the users be able to avoid setting the `technical` claims like `aud` (similarly to how it has already been done with `iss`)
=> Add a smallrye.jwt.new-token.audience property

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalUtils.java
Fixes #362
This PR only moves the code which updates the claims based on some smallrye-jwt specific properties as well as sets a raw token.
This is to help the users who write the custom factories in order to skip the token validation but still wish to apply these `post-verification` properties.
I'd like to release `2.4.2` once #376 and this PR get merged
=> Add PrincipalUtils

implementation/jwt-auth/src/main/java/io/smallrye/jwt/SmallryeJwtUtils.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
This is the last PR which I'd like to target at the `mpjwt12` branch. It updates `JwtAuthContextInfoProvider` and:
- removes `Optional` where possible (Mike - thanks for pointing it earlier on)
- removes the redundant getters - they do not even cover all the properties - they were originally intended for Thorntail and even there there were not property integrated as far as I recall
- drops the deprecated property which has already been deprecated in the `2.x` line
=> Remove Optional for the config properties with the default values

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtClaimTypeVerifierTest.java
Fixes #391
I've been thinking for a while what exactly would be the right course of action when someone types `.claim("sub", 1)` and decided that instead of silently converting to String and causing some potentially difficult to diagnose problems it would be better to enforce the correct types for only those claims which are well-known (ex JWT and Mp JWT specs) but more importantly those which are directly (have the dedicated setters) supported by this API - this will also ensure the consistent handling of such claims, whether they set in a typed way or as Objects.
A few simple claims must be Strings, `aud` or `groups` - Strings or Collections of Strings, `iat` and `exp` - `long` or `Instant`.
Also improved the documentation. And added `claim` setters accepting `Claims` as a claim name
=> Enforce types of the directly supported claims when they are set as Objects

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplLogging.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #395 
Fixes #404 
this PR aligns the sign/encrypt key properties with the convention used for configuring the verification/decryption keys, deprecates an inner-sign none signature mode which can only add to the confusion, and cleans up some docs
=> Fix configuration key location inconsistency and deprecate the inner-sign none signatures

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java
This is the very last PR into the `mpjwt12` branch. It affects `implementation/jwt-build` module only.
Support for the deprecated `none` innger-sign algorithm is dropped, and the deprecated  sign/encrypt `key-location` properties. are also dropped.
=> Remove deprecated JWT Build API inner-sign none signature support and key location properties

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipalFactory.java
When loading an instance of JWTCallerPrincipalFactory via the `ServiceLoader`, that instance will need to be registered under the `io.smallrye.jwt.auth.principal.JWTCallerPrincipalFactory` entry in `./META-INF/services/`.
The logging component for this, however, makes use of an incorrect path for that resource. (There is no such `org.eclipse.microprofile.jwt.principal.JWTCallerPrincipalFactory` class or interface.)
=> Use correct resource location for service loader logging of JWTCallerPrincipalFactory

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
@radcortez @darranl @MikeEdgar 
This PR follows #413 and actually completes the removal of these 2 deprecated properties in 3.0.0. I've run Quarkus `microprofile-4` branch and I did not see the failing tests which rely on those deprecated properties so I realized the previous PR was not complete. Roberto, Darran, I've got your approval to the earlier PR so I'll go ahead with merging this one once it passes the builds - the updates are very simple - the drop the properties typed as `DEPRECATED_...` in the code :-)
=> Complete the removal of smallrye.jwt.sign.key-location and smallrye.jwt.encrypt.key-location properties

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTTokenParser.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
Fixes #427 
When a invalid public key has been configured in the `mp.jwt.verify.publickey.location`, an `UnresolvableKeyException` should be reported. However, if this exception arises inside the call to the JOSE method, then the `UnresolvableKeyException` gets wrapped in a `InvalidJwtException` by the JOSE method, resulting in the wrong error code being sent in `JWTHTTPAuthenticationMechanism.`
=> Issue#427 DefaultJWTTokenParser#parseClaims Exception Handling

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #420
This PR supports making the `new-token.issuer` and `new-token.audience` override the existing claims, such that, for example, in `quarkus-oidc-token-propagation` I can code:
```
@Inject JsonWebToken jwt;
String newJwt = Jwt.claims(jwt).sign();
```
and doc that the users - if they need this feature, should only configure the new signing key, and/or issuer and audience
etc.
Totally isolated to `jwt-build`
=> Add smallrye.jwt.new-token.override-matching-claims property

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
I thought I did remove all the deprecated methods/classes but with all the 3.0.0 pre-release activity, this long time deprecated method has been left around.
It was deprecated for at least 4 months, and its specification is weak and difficult to implement correctly, and the point of this method is also hard to justify. So I'd like to avoid smallrye-jwt carrying it around for another year or so :-) before we have 4.0.0 :-).
I honestly don't expect anyone be affected by it, i.e don't think the users have started using a deprecated `.json()` method during the last few weeks in 3.0.0
CC @darranl Darran, 100% not related to MP JWT 1.2
=> Remove a long time deprecated JwtClaimsBuilder.json() method

doc/modules/ROOT/pages/generate-jwt.adoc
`smallrye.jwt.encrypt.key-location` and `smallrye.jwt.sign.key-location` are deprecated, so the documentation should refer to the new configuration keys.
Related #413 #416
=> Documentation: Replace deprecated configuration keys

README.adoc, doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java
=> Update README to refer to MP JWT 1.2 and remove the references to RSA-OAEP-256 being the default key enc algorithm

implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptJwkTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignJwkTest.java, implementation/jwt-build/src/test/resources/privateKeyA128KW.jwk, implementation/jwt-build/src/test/resources/privateKeyHS512.jwk
Fixes #321.
This PR makes sure that `alg` and `kid` properties do not have to be set manually when `JWK` keys are used to sign or encrypt the claims and those keys have already either `alg` and/or `kid` set. 
`KeyUtils` have been updated a bit - none of that code is used by the server side MP JWT code.
Also CC @SoniaZaldana
=> Use JWK 'alg' and 'kid' when creating JWT if these headers are not set

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignature.java
this PR removes (hopefully) the last references to the properties which are no longer supported in JWT build API
=> Removing more references to 'smallrye.jwt.sign.key-location' and 'smallrye.jwt.encrypt.key-location'

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryptionBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #463.
Note I've added a note that the encryption builder should not be reused - this is because it operated on a `String`, example, it can already be a signed JWT.
It does not mean one can not get a unique `jti` when encrypting the tokens, it is only about recommending to avoid (not very likely to happen) pattern:
```
JwtEncryptionBuilder builder = Jwt.upn("alice").innerSign();
builder.keyId("1").encrypt();
builder.keyId("2").encrypt();
```
the same can be done by simply doing 
```
Jwt.upn("alice").innerSign().keyId("1").encrypt();
Jwt.upn("alice").innerSign().keyId("2").encrypt();
```
or
```
JwtClaimsBuilder builder = Jwt.upn("alice");
builder.innerSign().keyId("1").encrypt();
builder.innerSign().keyId("2").encrypt();
```
=> Ensure JWT ID is unique when the claims or signature builder is reused

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptJwkTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignJwkTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java, implementation/jwt-build/src/test/resources/privateEncryptionKeys.jwks, implementation/jwt-build/src/test/resources/privateSigningKeys.jwks
Fixes #462
After looking at the code again I thought of addressing #462 by only caching PEM configured keys since there could be no ambiguities but decided to avoid caching JWK keys as their key identifiers can vary between the requests, in theory at least, so the only optimization when dealing with the JWK keys is when they are loaded from a multi-key JWK set - where new `smallrye.jwt.sign.key.id`/`smallrye.jwt.encrypt.key.id` can help with simplifying the code - as setting `kid` is a technical operation
I'm planning to release `3.2.0` after this PR is merged
=> Cache configured PEM keys and check configured kid for JWK keys

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java
Fixes #493
Right now the docs say it is `RSA_OAEP` while the code continues using `RSA_OAEP_256` by default - and it causes confusions when MP JWT server, assuming `RSA_OAEP` is indeed a default one, fails to decrypt.
I might do `3.3.0` after it as opposed to `3.2.2`.
=> Using the correct default key encryption algorithm

implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/ConfigMessages.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Fixes #507.
Quarkus user had to set `mp.jwt.verify.publickey.algorithm=HS512` which does not look correct even though it works, so I've un-deprecated the usage of `smallrye.jwt.verify.algorithm` for setting `HS256/384/512`
=> Undeprecate smallrye.jwt.verify.algorithm for setting HMAC algorithms

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignPS256Test.java
Fixes #514
This PR lets configure the signature and key-encryption algorithms to simplify the code; 
Also removes redundant `none` signature code - it is not supposed to be supported for a while but this code was hanging there (at some point one could inner-sign with none and then encrypt - which makes the inner-sign pointless since it is there to prove who signed the encrypted payload - so none should not have been available in the code by now anyway); and tightened a bit the encryption algorithm check the same way it is done for the signature one - to have less verbose error exceptions when the algorithm is manually set to say `A128KW` requiring a secret key while the public RSA key is provided, etc
=> Add jwt build signature and key encryption algorithm properties

pom.xml, testsuite/tck/pom.xml
Additionally switch to WildFly 25.0.1.Final.
This is a follow up to https://github.com/smallrye/smallrye-jwt/pull/256
I have simplified this to the point that the provisioned server is very similar to the servlet distribution previously used.
The war which is deployed for the TCK is quite large, a follow up approach would then be to start to add Galleon layers so dependencies can move from the war ideally slimming the war to the point it only contains SmallRye artefacts. early contenders would be:
- CDI
- Rest
The EE Security integration could also be utilised which is closer to how WildFly pulls this in to enable JWT.
=> Issue#253 Convert project to use Galleon based provisioning instead of a zip download and extraction.

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignature.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #524 
This PR adds  `smallrye.jwt.sign.key` and `smallrye.jwt.encrypt.key` properties for the users be able to substitute the parameterized values of these properties with the values fetched from the external sources (example, Vault, as requested by a Quarkus user). Especially it can be of interest when signing the tokens in order to avoid managing the private keys on the local system.
PR is quite simple - for `sign()`, `innerSign()` (delegates to `sign()`) and `encrypt()` the location will be checked first and if it is not set - then the inlined content with the new properties.
Updated the tests and docs.
=> Add smallrye.jwt.sign.key and smallrye.jwt.encrypt.key properties

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtEncryption.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java
Fixes #519
This PR follows #514 and just adds a new property to support the content encryption algorithm; some doc typos have been fixed as well
=> Add smallrye.jwt.new-token.content-encryption-algorithm property

doc/modules/ROOT/pages/configuration.adoc
Fixes #521
This PR adds a note to clarify how to use the parser when the verification requirements are dynamic
=> Update JWTParser doc section with a note about DefaultJWTParser

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #552 (to let users relax the verification when they have no control over choosing the keys/secrets. Note I've dropped an explicit RSA key check from the encryption code as it is done now by Jose4J itself - which has also been the case with the signature implementation - I think I may've forgotten to remove it earlier)
Fixes #535 (just trimming the location values as one user had some space and could not load the keys)
This is the last update I'd like to do before releasing 3.3.3
=> Allow to relax the JWT build keys verification

.github/workflows/build.yml, pom.xml, testsuite/tck/pom.xml, testsuite/tck/src/test/java/io/smallrye/jwt/tck/SmallRyeJWTArchiveProcessor.java, testsuite/tck/src/test/resources/jetty-web.xml
This allows running the TCK with Jetty
The motivation is to be able to run the TCK with Jakarta, since there is no release with source-based Jakarta for Wildfly.
https://github.com/smallrye/smallrye-jwt/tree/jakarta
=> Run TCK with Jetty

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/jwt-auth/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
Fixes #571
Fixes #581
Currently only certificates in PEM format are supported and read from the file, but in the future we can support loading them from the truststores 
CC @kdubb
=> Support for TLS certificates and hostname verification

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/jwt-auth/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
Fixes #460
`Jose4J`'s `Get` class accepts `Proxy` (no control over the authentication though), so it makes sense to fix this long pending issue  since we have just added the config for TLS certs/hosts too.
Default proxy host is 80, same as it is done for Vertx
=> Support for HTTP Proxy

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Mike @MikeEdgar has proposed that a `client` qualifier is used in the configuration namespace for TLS, it indeed makes it clearer that they only affect the (http) client (currently when fetching JWKs, to be improved for fetching PEM keys too)
=> Use smallrye.jwt.client.tls namespace for configuring TLS

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/AbstractKeyLocationResolver.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, implementation/jwt-auth/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
Fixes #595.
@MikeEdgar Hi Mike, I'm keeping #593 open, in case we'd like to go ahead and support random URL schems via the custom resolvers.
I've updated one of the unit tests to check a new property since there is another test there which checks the certificate path
=> Add smallrye.jwt.client.tls.certificate to support inlined TLS certificates

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
This simple PR makes sure the decryption keys can be inlined directly in the configuration the same way it can be done for the verification keys - the motivation is to support a simple extraction of both verification and decryption keys from DB and other sources via `ConfigSource` as one of the users can not verify the inner signed tokens with the keys available in DB. The same was done earlier for `smallrye-jwt-build`. 
Perhaps support for custom KeyLocationResolvers can also be introduced in the next stage, I think Mike tried it earlier but I was concerned about exposing Jose4j specific details
=> Support for an inlined decryption key

implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Minor follow up to the keystore related code: if both the inlined key is null and the key location is null but the keystore alias (and password for the private keys) are set then attempt to load from a default store. It is to support this code:
https://docs.oracle.com/en/java/javase/17/security/pkcs11-reference-guide1.html
Right now one needs to point to the existing keystore location and it is not obvious reading the NSSDB as an InputStream and loading KeyStore from it will work or is sound as this DB may be large
CC @pjgg
=> Support for reading from default Keystore

implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java
CC @pjgg
This PR updates the code which loads `Keystore` to use a `Provider` instance instead of a string, and also adds as an option to load from a `null` (default) KeyStore to `smallrye-jwt-build` (as a follow up to #606 which missed it and only added this support for the verification part)
=> Use a Provider instance instead of a provider string in KeyStore.getInstance

doc/modules/ROOT/pages/configuration.adoc
=> Fix smallrye.jwt.client.tls.hosts property name typo in the docs

implementation/common/src/main/java/io/smallrye/jwt/util/JWTUtilMessages.java, implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java
Defaulting to a null provider if the configured/requested provider is not found makes it more difficult to debug 
CC @pjgg
=> Fail loading the keystore if no configured provider is found

implementation/common/src/main/java/io/smallrye/jwt/algorithm/SignatureAlgorithm.java, implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/ImplMessages.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java, implementation/jwt-build/src/test/resources/edEcPrivateKey.jwk, implementation/jwt-build/src/test/resources/edEcPublicKey.jwk, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java, testsuite/basic/src/test/resources/edEcPrivateKey.jwk, testsuite/basic/src/test/resources/edEcPublicKey.jwk
This PR adds a support to the EDDSA family of signature and encryption algorithms now also supported at the jose4j level.
EDDSA and its Ed25519 variant is considered to be one of the most secure and compact modern signature algorithms.
Good overview is for ex here:
https://cryptobook.nakov.com/digital-signatures/eddsa-and-ed25519
FYI, GitHub now uses Ed25519 with SSH keys: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
I'd like to release smallrye-jwt once this PR is merged
=> Add support for EDDSA

to-jakarta.sh
On main it is set to `1.0.0.Final`
=> Do not override version.arquillian.jetty in to-jakarta.sh

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #419.
I've been planning it for a while, removing a claim can be handy when the builder was initialized from more than one claim, example, from the injected `JsonWebToken`, and not all of the original claims have to make it into a new token, for example:
```
@Inject
JsonWebToken inJwt;
String outJwt = Jwt.claims(inJwt).remove("phone").sign();
```
etc.
I'd like to release `4.3.0` once this PR is reviewed, merged
=> Allow removing claims when bulding JWT

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #725 
This PR provides a typed support for a `scope` claim whose origins are in OAuth2 but is used by OIDC providers.
For example, instead of writing a code like this:
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-tenancy/src/test/java/io/quarkus/it/keycloak/ServicePublicKeyTestCase.java#L28
I'd like to write
`Jwt.scope("read:data")`, etc.
This PR also simplifies a bit the implementation of `groups` setters
=> Support for the scope claim in JWT Build API

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTParser.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalMessages.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTParserTest.java
I've had 2 user requests over may be the last 6 months where users would like to use `JsonWebToken` API but without doing another round of verification (ex in various AWS setups) but also without registering custom factories which can be used such purposes.
A simple `parseOnly` method is added to `JwtParser` to support such cases
=> Support parsing already verified tokens

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipal.java
=> Explain in JWTCallerPrincipal#getName JavaDocs that this method may not return a unique principal name

.github/project.yml
Proposing a version bump from 4.3.1 to 4.4.0 as 2 public interfaces got updated with new methods
=> Release SmallRye JWT 4.4.0

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTCallerPrincipal.java
JavaDocs does not like `or {@link JsonWebToken#getClaim("upn")}`
=> Fix JWTCallerPrincipal JavaDocs

implementation/common/src/main/java/io/smallrye/jwt/util/JWTUtilLogging.java, implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/common/src/main/java/io/smallrye/jwt/util/ResourceUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignPS256Test.java
Fixes #746
This PR logs when the file system resource is not found, and prevents NPEs in a few places where a null stream can be consumed, exceptions will be thrown in those places eventually too.
I'll release 4.4.0 once this PR is merged
=> Improve handling of file system resources

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtClaimTypeVerifierTest.java
Spec states the `exp` claim to be:
```
A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time,
ignoring leap seconds. This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented. See RFC 3339
[RFC3339] for details regarding date/times in general and UTC in particular.
```
=> Instant claims may be non-integer values

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipalTest.java
When integrating with Jetbrains Hub as an OpenID provider, found that it returns the time fields in the JWT as seconds since epoch and miliseconds in the decimal part.
Example:
"exp": 1712762861.532,
"iat": 1705105035.125,
"auth_time": 1704986861.532,
This was causing a `org.jose4j.jwt.MalformedClaimException` to be thrown as `Double` can't be cast to `Long` at first sight this seems a bug in the OpenID provider, but the spec is vague about the definition.
A JSON numeric value representing the number of seconds from
1970-01-01T00:00:00Z UTC until the specified UTC date/time,
ignoring leap seconds. This is equivalent to the IEEE Std 1003.1,
2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
which each day is accounted for by exactly 86400 seconds, other
than that non-integer …
=> Parse time claims as Number and convert to Long.

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtSignatureBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #770
This PR makes it easy to set a `jwk` token header, and is also a preparation for the DPoP work.
I'll be planning to do a release once this PR is reviewed and merged
=> Support for the 'jwk' JWT header

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTParser.java
Fixes #765 
Hi @MikeEdgar Can you please review this is very last PR before the release ? It only adds JavaDocs as users may be thinking the factory is managed somehow when this parser is created directly in the user code. 
It also fixes a possible NPE if the constructor accepting the factory only is used. This constructor supports methods like `parse(token, myPublicKey)` where a new context is created in any case, but if this constructor is used with `parse(token)` which is meant to be used with the injected JWTParser only, then it will cause NPE, so this PR prevents it
=> Add JavaDocs to DefaultJWTParser constructors and prevent possible NPE

.github/workflows/build.yml
Fixes #777.
I see JWT is attempting to review it, will it try to start a new release ?
=> Fix the Sonar plugin integration

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtEncryptionImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #784
Signature algorithm configuration is ignored if the signing key is not passed directly or if it is not set as a header property (ex, `Jwt.claims("claims.json").jws().algorithm(SignatureAlgorithm.ES256)`) and must be loaded, thus anything but RS256 will fail. So this PR checks the configuration property early if the header is not already set.
Not a problem for the encryption case.
=> Check configured signing algorithm when reading the key

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
add option to fetch Verification keys only once via ContextProvider. This option is disabled by default for backwards compatibility.
Resolves #478
Contributes to https://github.com/quarkusio/quarkus/issues/36352
=> fetch keys in ContextProvider

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java
=> Fix JwtClaimsBuilder.algorithm() implementation

implementation/common/src/main/java/io/smallrye/jwt/algorithm/SignatureAlgorithm.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtSignatureImpl.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
This fixes `java.lang.IllegalArgumentException: No enum constant
io.smallrye.jwt.algorithm.SignatureAlgorithm.EdDSA` when `EDDSA` is set through
`smallrye.jwt.new-token.signature-algorithm` property, or when it is set with
`JwtClaimsBuilderImpl`.
Currently, `JwtSignatureImpl.getConfiguredSignatureAlgorithm()` returns
algorithm name as a String from `SignatureAlgorithm.algorithmName` field,
in case of it being loaded from a configuration file.
If the algorithm was set through `JwtClaimsBuilderImpl`, the value is returned
as-is from the header, which means `EdDSA`, because this is how
`JwtClaimsBuilderImpl` puts the value there.
This name is then used to get appropriate `SignatureAlgorithm` enum variant
in `JwtSignatureImpl.getSigningKeyFromKeyContent(String)`, but without
using …
=> Fix IllegalArgumentException when using EdDSA signature algorithm

doc/modules/ROOT/pages/configuration.adoc, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/JWTAuthContextInfo.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/KeyLocationResolver.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/ConfigLogging.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java, testsuite/basic/src/test/java/io/smallrye/jwt/auth/principal/KeyLocationResolverTest.java
It will make it possible to use env vars to pass the signing secret key information, as asked for in https://github.com/quarkusio/quarkus/discussions/42550.
In fact, passing the secret key content using the public key property also works but it is not great asking users to use that property
=> Add smallrye.jwt.verify.secretkey property for inlining secret keys

implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Hi Mike, I thought it could cause some confusion since all other `@since` tags are attached to standard properties and refer to the MP JWT spec versions
=> Remove the @since tag for smallrye.jwt.verify.secretkey

implementation/jwt-auth/src/main/java/io/smallrye/jwt/config/JWTAuthContextInfoProvider.java
Fixes #817.
It is a minor follow up to #815.
In case of `HS256` the code on `main` checks if the resolvedLocation has been assigned to the MP JWT (public) key location property and fails if it is the case. But in #815, a new `smallrye.jwt.verify.secretkey` property is used thus the resolved location, even though it remains assigned by default to the MP JWT location, is `NONE`.
So this PR adds an extra check. Unfortunately tests in `testsuite/basic` for #815 are not using application.properties and it was missed. Tested at https://github.com/quarkusio/quarkus/pull/42629, though as suggested earlier, some good clean up of tests and also of the initial bootstrap code would have to be done at some point
=> Fix a key location comparison in case of HS256

implementation/jwt-build/src/main/java/io/smallrye/jwt/build/Jwt.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtClaimsBuilderImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtProviderImpl.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/spi/JwtProvider.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignEncryptTest.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #813.
This PR adds another method to the JWT builder API to simplify signing JSON strings.
For example, I've that often enough, in a test I have a JSON string ready (or it may be coming from DB) but we only have `Jwt.claims(Map)`, `Jwt.claims(JsonObject)` and `Jwt.claims(String jsonFileLocation)` start options - so I have to convert JSON String to JsonObject myself, which is not great.
=> Allow to build JWT from JSON string

implementation/common/src/main/java/io/smallrye/jwt/JsonProviderHolder.java, implementation/common/src/main/java/io/smallrye/jwt/util/KeyUtils.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/JsonUtils.java
https://github.com/smallrye/smallrye-jwt/pull/836 removed JsonProvider instantiation from JsonUtils, but KeyUtils is still instantiating a new json provider every time that we load JWKs... this PR creates a JsonProviderHolder in the common lib, and reuses that in JsonUtils and KeyUtils so we remove all JsonProvider re-instantiation from the project.
=> Use JsonProvider holder

implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/DefaultJWTCallerPrincipal.java, implementation/jwt-auth/src/main/java/io/smallrye/jwt/auth/principal/PrincipalLogging.java
When a numerical claim such as `updated_at` is presented as String by a provider like Auth0 (see https://github.com/quarkusio/quarkus/issues/43924), `smallrye-jwt` issues a warning, which is fair enough, since this and other standard claims are expected to be numbers, see the [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims), and MP JWT spec itself expects such claims be numbers (long), for example, [Claims.updated_at](https://github.com/eclipse/microprofile-jwt-auth/blob/main/api/src/main/java/org/eclipse/microprofile/jwt/Claims.java#L51).
What is a bit of a problem is that in https://github.com/quarkusio/quarkus/issues/43924 it happens during the implicit overridden toString() call and getting this warning is confusing given that probably noone is ever …
=> Add claimTypeMismatch log message

doc/modules/ROOT/pages/generate-jwt.adoc, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/JwtClaimsBuilder.java, implementation/jwt-build/src/main/java/io/smallrye/jwt/build/impl/JwtBuildUtils.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtBuildConfigSource.java, implementation/jwt-build/src/test/java/io/smallrye/jwt/build/JwtSignTest.java
Fixes #858
The issued at (`iat`), expiration time (`exp`) and `jti` claims are currently set by default if they have not already been set, but some token consumers are too sensitive to the presence of extra claims they don't process (even though, once the signature has been verified, the content is secure).
So I've added a property to make it possible to disable the addition of the default properties
=> Make it possible to disable adding default claims
